//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfOptionFourApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.MaterialsSupplier = new HashSet<MaterialsSupplier>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int IDSuppliersType { get; set; }
        public int INN { get; set; }
        public int QualityRating { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsSupplier> MaterialsSupplier { get; set; }
        public virtual SuppliersType SuppliersType { get; set; }
    }
}
